name: PR Queue Bot-main

on:
  workflow_dispatch:

jobs:
  check-prs-and-notify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/scripts
          sparse-checkout-cone-mode: false
